# My personal bashrc

export PERSONAL="$(readlink -f "${BASH_SOURCE[0]}" | xargs dirname | xargs dirname)"
export PATH="${PERSONAL}/bin:${PATH}"

if [ "$EUID" == 0 ]; then
    export DESKTOP="/home/ramya/Desktop"
fi

## Environment
export REPOS="${DESKTOP}/repos"
export OBSIDIAN="${DESKTOP}/obsidian"
export SCREENSHOTS="${DESKTOP}/screenshots"
export DROPBOX="${DESKTOP}/Dropbox"


export HOWTO="${PERSONAL}/share/howto"
export PATH="$HOWTO:$PATH"

if [ -e '/usr/local/cuda' ]; then export CUDA_HOME="/usr/local/cuda"; else export CUDA_HOME="/opt/cuda/"; fi
export PATH="$PATH:$CUDA_HOME/bin"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$CUDA_HOME/lib64"


### Ibus
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus


## My private dirs
dirs+=(
    [repos]="$REPOS"
    [obsidian]="$OBSIDIAN"
    [ss]="$SCREENSHOTS"
    [dropbox]="$DROPBOX"
    [howto]="$HOWTO"
    [imfind]="$REPOS/imfind"
    [airoot]="$REPOS/airoot"
    [shortcuts]="$REPOS/shortcuts"
    [nixos]="$REPOS/nixos"
    [hm]="$REPOS/home-manager"
    [personal]="${PERSONAL}"
    [personal/bin]="${PERSONAL}/bin"
    [personal/lib]="${PERSONAL}/lib"
    [personal/etc]="${PERSONAL}/etc"
)

## Aliases
alias brcp="$EDITOR ${PERSONAL}/etc/bashrc && source ${PERSONAL}/etc/bashrc"

alias yta='yt-dlp --extract-audio'
alias yt='yt-dlp'

alias ipyembed='echo "__import__(\"IPython\").embed()" | xc'
alias pca='pre-commit run --all-files'

alias use_llava='export IMFIND_USE_LLAVA="True"'

## Added by LM Studio CLI (lms)
export PATH="$PATH:/home/ramya/.lmstudio/bin"

## For lean
export PATH="$HOME/.elan/bin:$PATH"

